### ISSUE TITLE
wheel install fails on linux

### ISSUE THREAD

**Issue by ransomw** [ransomw/the-benevolent-dictators#45]
the wheel install has been tested on freebsd and windows.  it fails on linux with the following message

```
$ pip install -r dist/benevolent-0.0-py3-none-any.whl 
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 436, in get_requirements
    for parsed_req in parse_requirements(
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 148, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 335, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 340, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 371, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/req/req_file.py", line 549, in get_file_content
    content = auto_decode(f.read())
  File "/home/ransom/ws/gh/the-benevolent-dictators/.venv-install/lib/python3.10/site-packages/pip/_internal/utils/encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 70: invalid continuation byte

```

**Comment by ransomw** [comment]
`install *.whl` not `install -r *.whl`
